### ISSUE TITLE
Scene not displaying from ipython

### ISSUE THREAD

**Issue by vigji** [BrancoLab/brainrender#103]
**Describe the bug**
Scene not rendering inside ipython
**To Reproduce**
I am trying to open a viewer running the following lines (from an example) in ipython:

```python
brainrender.SHADER_STYLE = 'cartoon'
from brainrender.scene import Scene

# Create a scene
scene = Scene()

# Add the whole thalamus in gray
scene.add_brain_regions(['TH'], alpha=.15)

# Add VAL nucleus in wireframe style with the allen color
scene.add_brain_regions(['VAL'], use_original_color=True, wireframe=True)

scene.render()
```
What I get is the following:

```
Setting 'display_inset' to False as this feature is not                             available in juputer notebooks
Setting window size to 'auto' as whole screen is not available in jupyter
The scene is ready to render in your jupyter notebook
```

And nothing shows. This is worked around if I set `scene.jupyter=False` after instantiating it, but this sounds bizarre. It feels like brainrender is incorrectly inferring it is running from a notebook, I guess because of the line 
```
if vedosettings.notebookBackend == "k3d":
            self.jupyter = True
        else:
            self.jupyter = False
```
In the render class that returns true even outside a notebook.  Am I missing something?

**Comment by vigji** [comment]
Sorry, to have it working I need to add this:
```python
from vedo import embedWindow
embedWindow(False)
```

**Comment by FedeClaudi** [comment]
hey Luigi,

The [docs](https://docs.brainrender.info/usage/using-notebooks) are maybe not very clear on this, but `scene.render()` in Jupyter a doesn't actually render anything, it only "prepares the rendering".  To then render the scene you need:
```
from vedo import Plotter

vp = Plotter()
show(scene.actors)
```

I'm not sure if in iPython having `render` try to display the scene would work or if it would give the same error as in `Jupyter` as I never tested it, but from your message it sounds like with `scene.jupyter=False` it works? Is that so?

This:
```
if vedosettings.notebookBackend == "k3d":
            self.jupyter = True
        else:
            self.jupyter = False
```

Is to infer from `vedo` if we are using a notebook, instead of having the user provide this information, I guess however it doesn't discriminate between notebooks and iPython. 

---
```
from vedo import embedWindow
embedWindow(False)
```

Works because it changes the way the rendering is done: instead of a window embedded in your notebook it creates a pop up window, the same as what happens normally in a script. This doesn't involve using `k3d` so it's like setting `self.jupyter = False`.


---

I hope this clarifies things. In general I tend to discourage using notebooks and ipython because not all rendering features work with that (e.g. I don't think you'll get the `cartoon` style). I've been trying to support Jupyter nonetheless but I never tested iPython.

**Comment by vigji** [comment]
Oh, I see! For some reason I was expecting the behavior of iPython to be the same of running a script in terms of the backend things, but it is actually not; so I thought code from the examples should work from there as well. For notebooks yes, I had in mind having to use the Plotter, so no need for further clarification on docs for that!

> In general I tend to discourage using notebooks and ipython because not all rendering features work with that (e.g. I don't think you'll get the cartoon style). I've been trying to support Jupyter nonetheless but I never tested iPython.

Makes perfect sense, will use scripts! :)
