### ISSUE TITLE
variables.py may not be editable with a pip install

### ISSUE THREAD

**Issue by adamltyson** [BrancoLab/BrainRender#26]
`variables.py` can't always be edited with a pip install (and certainly not easily). It would be easier if this was e.g. a config file in `.brainrender`.

**Comment by FedeClaudi** [comment]
Changed the behaviour:

1. default values are now saved to `brainrender.default_variables.py`
2. importing brain render will crate a `config.yaml` file in `.brainrender` if this doesn't exist yet. This file will store the value of the variables used for rendering and can be edited by the user
3. In the code the variables stored in `config.yaml` can now be with `from brainrender import *` instead of `from brain render.variables import *`

Let me know if it doesn't work or you spot something that needs changing.

**Comment by adamltyson** [comment]
All looks to work perfectly on my end.
