### ISSUE TITLE
NEURON_FILE not found

### ISSUE THREAD

**Issue by alejoe91** [BrancoLab/BrainRender#33]
Hi @FedeClaudi 

After a fresh install (I tried both pip and setup form source), ifI try to `import brainrender` I get this error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-701461d58470> in <module>
----> 1 import brainrender

~/Documents/Codes/BrainRender/brainrender/__init__.py in <module>
     95         continue
     96     if par not in params.keys():
---> 97         params[par] = defaults[par]
     98 save_yaml(params_file, params, append=False, topcomment=comment)
     99 

KeyError: 'NEURONS_FILE'

In [2]: %debug                                                                                       
> /home/alessio/Documents/Codes/BrainRender/brainrender/__init__.py(97)<module>()
     95         continue
     96     if par not in params.keys():
---> 97         params[par] = defaults[par]
     98 save_yaml(params_file, params, append=False, topcomment=comment)
     99 
```

Am I missing something? 

BTW, the preprint looks super cool! 

Cheers
Alessio

**Comment by FedeClaudi** [comment]
Hi, 

Thank you for picking this up and for letting me know. 

I should have fixed this now, could you please try installing this version of brainrender:
```
pip install brainrender==0.3.3.6b0
````
and trying again?

> BTW, the preprint looks super cool!
Thank you !
One of the goals behind brainrender was to make something that can be used to generate high quality figures, so I'm happy to hear that. 

Cheers, 
Federico

**Comment by alejoe91** [comment]
With the 6b version it works :)

**Comment by FedeClaudi** [comment]
awesome, will release the updated version then, thanks for testing!

**Comment by alejoe91** [comment]
Looking forward to the support of .swc files!
(and maybe .asc files for Blue Brain models?)

**Comment by FedeClaudi** [comment]
.swc files are supported, but I haven't documented this properly. 

You can use the standard `Scene()` class to render `.swc` files by passing the file's path to `scene.add_neurons`. 

However since generally morphologies from `.swc` are not registered to the allen atlas there's also another class that is dedicated to visualising this without the rest of the atalas.
You can use the `AllenMorphology` to:
1) Download morphology data from the Allen Cell Types database as .swc files
2) Render any .swc file (e.g. those from neuromorpho.org)

A brief example:
```
from brainrender.Utils.AllenMorphologyAPI.AllenMorphology import AllenMorphology

am = AllenMorphology()
neurons = am.download_neurons(am.neurons.id.values[:3])
am.add_neuron(neurons, color='salmon')
am.render()
```

Hope this helps, will add an example on how to use this class in more details.
