### ISSUE TITLE
Create blank settings file on first use so user's settings aren't being tracked by Git

### ISSUE THREAD

**Issue by raacampbell** [BrancoLab/BrainRender#4]
Right now changes to the settings.py are tracked by Git. Instead, I'd suggest a settings directory or file that isn't under version control. It can be populated automatically on first run with a default settings file.

**Comment by FedeClaudi** [comment]
Hi, 

I'm not sure what you mean exactly by this?
I've edited `settings.py` so that it doesn't have any path saved by default on it. 
You can then use the `update_folders` function to set the paths as desired during run time, so that you don't have to edit `settings.py`. Did you have a different solution in mind?

**Comment by raacampbell** [comment]
Ok, odd. The settings.py on my machine had a path on your PC in it for some reason. I can see that the settings.py in the repo is empty. Somehow something added your path. I will try to work out how that happened. 

The more general point I had, however, was that settings.py is under version control and it's the main settings file. So if I choose to edit it my changes will potentially be logged by Git.

**Comment by raacampbell** [comment]
Oh, I see! You just removed it in d4e4fdc92867f1d3052b6a4b15e389064a5126eb

**Comment by FedeClaudi** [comment]
Yes I did, after your comment. I have just updated `settings.py` so that users can specify their path using `update_folders` [which is now under `BrainRender.Utils.data_io.py`. 

This way users can easily specify their working path without having to edit `settings.py` and thus avoiding being logged by Git. It's a bit of a messy workaround though, so if you have a cleaner solution please let me know!

**Comment by raacampbell** [comment]
The solution I have is for situations where you want to allow the user to edit a settings file but avoid it being under version control. If you don't ever need to edit the file then there's not much to be gained with what I do. I don't have a nice package to handle this, just a process that I've implemented two or three times in the past. 

All I do is create a settings file in, say, `~/.brainRenderSettings`, and tell the user to edit on first run. There is a default settings file in the repo so if you later add fields not present in the user's file then these default ones can be used instead.

**Comment by FedeClaudi** [comment]
I see, thanks. 
I'll think about it but for now I'll leave it as is. 

Thanks, 
Federico
