### ISSUE TITLE
BrainRender crashes on rendering when used over remote desktop

### ISSUE THREAD

**Issue by johnmbarrett** [BrancoLab/BrainRender#52]
Hi, so the preprint looks cool and I was excited to play with this, but for obvious reasons I am working from home right now and so ran into this error trying to use BrainRender on my lab computer that I remote desktop into.

Steps to reproduce:

1) Log into a machine using Windows' built-in remote desktop client (n.b. I think this has to be a new login, i.e. logging into a session that was started locally won't cause the error--I had restarted the remote PC for unrelated reasons before installing BrainRender)
2) Install brainrender if not already installed
3) Go to command prompt and enter `python`
4) Enter the following:
```
from brainrender.scene import Scene
scene = Scene()
scene.render()
```
Expected behaviour: a Scene is rendered

Actual behaviour: an error window pops up (see screenshot below) for a few seconds, then python crashes.

![brainrender error](https://user-images.githubusercontent.com/19190699/79155952-91ed4080-7d97-11ea-95cf-a2271fea5db9.png)

Additional info: this is related to [a known issue](http://vtk.1045678.n5.nabble.com/Remote-Desktop-and-the-VTK-window-td5746557.html) with VTK and Windows remote desktop. Various workarounds are suggested in that thread and elsewhere on the internet. There's not much that can be done about this from BrainRender's perspective short of falling back to a completely different rendering system when this happens (which I assume would be very hard), but it should at least be possible to catch this error and exit gracefully, possibly popping up a warning saying that remote desktop is unsupported, rather than crashing like this.

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for raising this issue, I haven't seen it before. 

I think you're right, there's a few applications that won't work over remote desktop, and VTK seems to be one of these. 

I agree that this sould be handled more gracefully, but I think that the problem is within vtk/vtkplotter so I'm not sure if I can catch it from brainrender if python crashes. 

Either way, I'm sorry this happening at a time when working from home is the only option. I think you're best option would be to try and get the data you need for the rendering to your local machine, or perhaps trying other ways to control your remote machine (e.g. teamviewer).

**Comment by marcomusy** [comment]
..maybe this can be of any help: https://github.com/marcomusy/vtkplotter/issues/88

**Comment by FedeClaudi** [comment]
hi @johnmbarrett  did you get a chance to try what marco suggested? Did it help?
