### ISSUE TITLE
Rendering a specific range of the brain

### ISSUE THREAD

**Issue by jt522** [BrancoLab/BrainRender#87]
Hello,

Is it possible to render a specific  range of brain instead of cutting at certain plane?
For example, I would like to render the coronal brain between AP 4mm to 5mm.

Thanks!

**Comment by adamltyson** [comment]
Hi fellow penguin. @FedeClaudi I'd also like to know this.

**Comment by FedeClaudi** [comment]
Hi, 

What you can do is use two planes, if you cut with one at the time you are left with the region inbetween. You want to be careful about how you define them though. For what you need, they should be parallel to each other (at some fixed offset) and with norms facing in opposite directions. This is important because the norm is what specifies which side of the plane is kept. 

Here's an example of how to do this:
```
import brainrender
from brainrender.scene import Scene
import numpy as np

brainrender.SHADER_STYLE = 'cartoon'

scene = Scene()

# Add brain regions
actors = scene.add_brain_regions(['MOs', 'MOp', 'SSs', 'SSp'])

# Get two points to anchor the planes
p0 = scene.atlas.get_region_CenterOfMass('MOs', unilateral=False)
p1 = scene.atlas.get_region_CenterOfMass('SSs', unilateral=False)

# Size of planes in x,y direction. Only useful to show the rendered plane
sx = float(np.diff(scene.atlas._root_bounds[2]))
sy = float(np.diff(scene.atlas._root_bounds[1]))

# Create planes with opposing norms
plane0 = scene.atlas.get_plane_at_point(p0, [1, 0, 0], sx, sy)
plane1 = scene.atlas.get_plane_at_point(p1, [-1, 0, 0], sx, sy)

# Cut with one plane at the time
scene.cut_actors_with_plane(plane0, actors=actors, close_actors=True, showplane=True)
scene.cut_actors_with_plane(plane1, actors=actors, close_actors=True, showplane=True)

# Change color of plane actors
for act in scene.actors['others']:
    act.c('salmon')

scene.render()

```
If you want to cut all actors, including `root`, then just don't use the `actors` keyword argument. Same goes for `showplane` if you don't want to visuailise the planes. If you set `close_actors=False` the actor's meshes won't closed after cutting which means you can see inside them. 

A bit of advice to improve the looks of the rendering: if you decide to cut the `root` mesh as well I suggest doing it in two steps:
```
scene.cut_actors_with_plane(plane0, actors=scene.root, close_actors=False)
scene.cut_actors_with_plane(plane0, actors=actors, close_actors=True)
```

Otherwise where the actors are 'closed' after cutting the root mesh will intersect the others, and this yields weird effects when rendering. 

----
Note that brainrender's mouse brain functionality relies on the allen brain atlas which is not defined relative to bregma (see [here](https://community.brain-map.org/t/why-doesnt-the-3d-mouse-brain-atlas-have-bregma-coordinates/158) for a discussion on the topic). So you can't directly define the region you're interested in in AP coordinates.

**Comment by jt522** [comment]
Thanks for your quick response!
Sorry for a dumb question.
Where can I set AP range? 
For example, I want to render AP inbetween 11000.0 to 13000.0 (Allen coordinates).

Thanks!

**Comment by FedeClaudi** [comment]
You do that by specifying the position of `p0` and `p1` (e.g. `p0 = [11000, 0, 0]` should work, if not try one of the other coordinates.

**Comment by jt522** [comment]
Great, Thanks!

**Comment by jt522** [comment]
Actually one more question. 
Can I avoid using these two lines?
p0 = scene.atlas.get_region_CenterOfMass('MOs', unilateral=False)
p1 = scene.atlas.get_region_CenterOfMass('SSs', unilateral=False)

If cutting planes only depend on AP coordinates I set, it would be great.

Thanks!

**Comment by FedeClaudi** [comment]
If you know where you want the planes to be, you can use 0 lines!

```
plane0 = scene.atlas.get_plane_at_point([x, y, z], [1, 0, 0], sx, sy)
```
where `[x, y, z]` is the coordinates of you point the plane will be at.  If you only care about, say, the `x` direction then you can use `[x, 0, 0]`.

Finally, one thing that miget be of help is setting `brainreder.SHOW_AXES=True` before you create the `Scene`, this way you can see the `x`, `y` and `z` axes of your scene.

**Comment by jt522** [comment]
Thanks @FedeClaudi! Everything works great.

**Comment by FedeClaudi** [comment]
awesome, get in touch if you have any question or need any help.
